services:
  - type: web
    name: oru-transcript-formatter
    env: python
    plan: free
    buildCommand: bash build.sh
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
    healthCheckPath: /
