services:
  - type: web
    name: oru-transcript-formatter
    env: python
    plan: free
    rootDir: .
    buildCommand: |
      pip install -r backend/requirements.txt
      cd frontend && npm install && npm run build
      cp templates/sample_formatted.docx backend/sample_formatted.docx
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
    healthCheckPath: /
